[general]
import = [
    "~/AppData/Roaming/alacritty/catppuccin-mocha.toml",
    # "~/AppData/Roaming/alacritty/catppuccin-latte.toml",
]
live_config_reload = true

[terminal.shell]
program = "pwsh"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
